Vagrant.configure("2") do |config|
  # config.vm.box = "ubuntu/focal64"
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.provider "parallels"

  # Puppet Master
  config.vm.define "puppetmaster" do |master|
    master.vm.hostname = "puppetmaster.local"
    master.vm.network "private_network", ip: "192.168.56.10"
    master.vm.provider "parallels" do |prl|
      prl.memory = 2048
      prl.cpus = 2
    end
    master.vm.provision "shell", path: "provision_master.sh"
  end

  # Puppet Agent
  config.vm.define "puppetagent" do |agent|
    agent.vm.hostname = "puppetagent.local"
    agent.vm.network "private_network", ip: "192.168.56.11"
    agent.vm.provider "parallels" do |prl|
      prl.memory = 1024
      prl.cpus = 1
    end
    agent.vm.provision "shell", path: "provision_agent.sh"
  end
end