apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autopilot.gke.io/resource-adjustment: '{"input":{"containers":[{"name":"nginx-1"}]},"output":{"containers":[{"limits":{"ephemeral-storage":"1Gi"},"requests":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"name":"nginx-1"}]},"computeClassAtAdmission":"Default","modified":true}'
    autopilot.gke.io/warden-version: 33.33.20-gke.2
    deployment.kubernetes.io/revision: '1'
  creationTimestamp: '2025-12-17T06:50:55Z'
  generation: 1
  labels:
    app: nginx-1
    app.kubernetes.io/managed-by: cloud-console
  name: nginx-1
  namespace: default
  resourceVersion: '1765954329467743024'
  uid: a02b3277-43d6-4652-bfd3-de7cff63bea4
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nginx-1
      app.kubernetes.io/managed-by: cloud-console
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-1
        app.kubernetes.io/managed-by: cloud-console
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx-1
        resources:
          limits:
            ephemeral-storage: 1Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: amd64
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: '2025-12-17T06:50:55Z'
    lastUpdateTime: '2025-12-17T06:51:52Z'
    message: ReplicaSet "nginx-1-7bb7cfdbfb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: 'True'
    type: Progressing
  - lastTransitionTime: '2025-12-17T06:52:09Z'
    lastUpdateTime: '2025-12-17T06:52:09Z'
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: 'True'
    type: Available
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
