---
- name: Install Apache web server
  apt:
    name: apache2
    state: present
  become: yes

- name: Start and enable Apache service
  service:
    name: apache2
    state: started
    enabled: yes
  become: yes

- name: Deploy index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  become: yes
  notify: restart apache
